# Generated by Django 5.0.4 on 2024-04-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('picture', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('fatal', 'Fatal')], max_length=20)),
                ('client_ip', models.CharField(max_length=255)),
                ('action', models.TextField()),
                ('user_mail', models.EmailField(max_length=255)),
                ('current_page', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('student', 'Student'), ('librarian', 'Librarian'), ('superadmin', 'Super Admin')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('cycle', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('catalogue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblieti.catalogue')),
                ('author', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=20)),
                ('publication_year', models.IntegerField()),
            ],
            bases=('biblieti.catalogue',),
        ),
        migrations.CreateModel(
            name='BR',
            fields=[
                ('catalogue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblieti.catalogue')),
                ('resolution', models.CharField(max_length=10)),
            ],
            bases=('biblieti.catalogue',),
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('catalogue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblieti.catalogue')),
                ('artist', models.CharField(max_length=100)),
                ('tracks', models.IntegerField()),
            ],
            bases=('biblieti.catalogue',),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('catalogue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblieti.catalogue')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            bases=('biblieti.catalogue',),
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('catalogue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblieti.catalogue')),
                ('director', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
            ],
            bases=('biblieti.catalogue',),
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('commentary', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblieti.user')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_loan', models.DateTimeField()),
                ('date_of_return', models.DateTimeField()),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblieti.catalogue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblieti.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblieti.catalogue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblieti.user')),
            ],
        ),
    ]
