# Generated by Django 5.0.4 on 2024-04-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblieti', '0002_alter_booking_booking_date_alter_catalogue_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='br',
            name='resolution',
            field=models.CharField(max_length=100),
        ),
    ]
