# Generated by Django 5.0.4 on 2024-04-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblieti', '0003_alter_br_resolution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_ieti',
        ),
    ]
