# Generated by Django 5.0.4 on 2024-04-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblieti', '0005_alter_user_ieti_options_alter_user_ieti_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ieti',
            name='mail',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user_ieti',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
