# Generated by Django 5.0.4 on 2024-04-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblieti', '0006_alter_user_ieti_mail_alter_user_ieti_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_ieti',
            name='mail',
        ),
    ]
