# Generated by Django 5.0.4 on 2024-05-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblieti', '0008_remove_logs_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='is_loanable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='school',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
