# Generated by Django 5.0.4 on 2024-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblieti', '0009_catalogue_is_loanable_catalogue_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='school',
            field=models.CharField(default='Institut Esteve Terradas i Illa', max_length=255, null=True),
        ),
    ]
