# Generated by Django 5.0.4 on 2024-05-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblieti', '0010_alter_catalogue_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='CDU',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
